"use client";

import { useCallback, useEffect, useState } from "react";
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui";

type ApiResult<T> = { success?: boolean; data?: T; error?: { message?: string } };
async function request<T>(url: string, method = "GET"): Promise<T> {
  const res = await fetch(url, { method, headers: method === "POST" ? { "Content-Type": "application/json" } : undefined });
  const body = (await res.json()) as ApiResult<T>;
  if (!res.ok || !body.success || !body.data) throw new Error(body.error?.message ?? "Could not load sales intelligence.");
  return body.data;
}

export function AccountIntelligencePanel({ accountId }: { accountId: string }) {
  const [data, setData] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setError(""); try { setData(await request("/api/clients/" + accountId + "/intelligence")); } catch (e) { setError(e instanceof Error ? e.message : "Could not load account intelligence."); } }, [accountId]);
  useEffect(() => { void load(); }, [load]);
  async function refresh() { setBusy(true); setError(""); try { const result = await request<Record<string, unknown>>("/api/clients/" + accountId + "/intelligence", "POST"); setData((old) => old ? { ...old, insight: result, stale: false } : old); } catch (e) { setError(e instanceof Error ? e.message : "Could not refresh."); } finally { setBusy(false); } }
  const account = data?.account as { name?: string; status?: string } | undefined; const insight = data?.insight as { supportingData?: { summary?: string }; recommendation?: string; result?: string; createdAt?: string } | null;
  const signals = data?.signals as string[] | undefined; const contacts = data?.contacts as Array<{ id: string; name: string; lastName: string | null; title: string | null; primary: boolean }> | undefined;
  const opportunities = data?.opportunities as Array<{ id: string; name: string; stage: string | null; amount: number | null }> | undefined;
  const empty = !contacts?.length && !opportunities?.length && !(data?.activities as unknown[] | undefined)?.length && !(data?.meetings as unknown[] | undefined)?.length && !(data?.followups as unknown[] | undefined)?.length && !(data?.tasks as unknown[] | undefined)?.length && !(data?.proposals as unknown[] | undefined)?.length;
  return <Card><CardHeader className="flex-col items-start justify-between gap-3 sm:flex-row"><div><CardTitle>Account intelligence</CardTitle><CardDescription>Evidence from this account’s CRM activity and records.</CardDescription></div><Button size="sm" variant="outline" className="shrink-0" onClick={refresh} disabled={busy}>{busy ? "Generating…" : "Refresh insight"}</Button></CardHeader><CardContent className="space-y-3">
    {!data && !error && <p className="text-sm text-muted-foreground">Loading account intelligence…</p>}{error && <p role="alert" className="text-sm text-danger">{error}</p>}
    {data && <><p className="text-sm">{account?.name} · {account?.status}</p>{insight ? <><p className="text-sm">{insight.supportingData?.summary ?? insight.result}</p><p className="text-sm text-muted-foreground">{insight.recommendation}</p><p className="text-xs text-muted-foreground">Generated {insight.createdAt ? new Date(insight.createdAt).toLocaleString() : "just now"}{data.stale ? " · Source data changed; refresh recommended." : ""}</p></> : <p className="text-sm text-muted-foreground">No saved account summary. Refresh to generate one.</p>}
      {empty && <p className="text-sm text-muted-foreground">Insufficient account activity for deeper signals.</p>}{Boolean(data.aiUnavailable) && <p className="text-xs text-muted-foreground">AI is unavailable; deterministic CRM signals remain available.</p>}
      <div className="flex flex-wrap gap-2">{signals?.map((s) => <span key={s} className="rounded-full bg-surface-subtle px-2 py-1 text-xs">{s}</span>)}</div>
      {!!contacts?.length && <p className="text-sm"><strong>Important contacts:</strong> {contacts.map((c) => c.name + (c.lastName ? " " + c.lastName : "") + (c.primary ? " (primary)" : "")).join(", ")}</p>}
      {!!opportunities?.length && <div><p className="text-sm font-medium">Open opportunities</p>{opportunities.slice(0, 5).map((o) => <p key={o.id} className="text-sm text-muted-foreground">{o.name} · {o.stage ?? "Stage unavailable"}</p>)}</div>}
    </>}
  </CardContent></Card>;
}

export function BuyingIntentPanel({ leadId }: { leadId: string }) {
  const [data, setData] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setError(""); try { setData(await request("/api/leads/" + leadId + "/buying-intent")); } catch (e) { setError(e instanceof Error ? e.message : "Could not load intent."); } }, [leadId]);
  useEffect(() => { void load(); }, [load]);
  async function refresh() { setBusy(true); try { setData(await request("/api/leads/" + leadId + "/buying-intent", "POST")); } catch (e) { setError(e instanceof Error ? e.message : "Could not refresh intent."); } finally { setBusy(false); } }
  return <Card><CardHeader className="flex-col items-start justify-between gap-3 sm:flex-row"><div><CardTitle>Buying intent</CardTitle><CardDescription>First-party signals recorded in this CRM.</CardDescription></div><Button size="sm" variant="outline" className="shrink-0" disabled={busy} onClick={refresh}>{busy ? "Refreshing…" : "Refresh"}</Button></CardHeader><CardContent className="space-y-2">{error && <p role="alert" className="text-sm text-danger">{error}</p>}{!data && !error && <p className="text-sm text-muted-foreground">Loading buying signals…</p>}{data && <><p className="text-lg font-semibold">{String(data.level)}{data.score !== null && data.score !== undefined ? " · " + data.score + "/100" : ""}</p><p className="break-words text-sm text-muted-foreground">{String(data.explanation)}</p><p className="break-words text-sm">{String(data.recommendedAction)}</p>{!(data.signals as unknown[]).length ? <p className="text-sm text-muted-foreground">Insufficient data: no recorded engagement signals.</p> : <ul className="list-disc pl-5 text-sm">{(data.signals as string[]).map((x) => <li key={x}>{x}</li>)}</ul>}<p className="break-words text-xs text-muted-foreground">Source: CRM records · {String(data.provenance)}{data.stale ? " · Data changed; refresh recommended." : ""}</p></>}</CardContent></Card>;
}

export function DailySalesIntelligence({ canViewReps }: { canViewReps: boolean }) {
  const [data, setData] = useState<Record<string, unknown> | null>(null); const [reps, setReps] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [coachingBusy, setCoachingBusy] = useState(false);
  const load = useCallback(async () => { setError(""); try { const d = await request<Record<string, unknown>>("/api/sales-intelligence"); setData(d); if (canViewReps) setReps(await request("/api/sales-intelligence?section=reps")); } catch (e) { setError(e instanceof Error ? e.message : "Could not load priorities."); } }, [canViewReps]);
  useEffect(() => { void load(); }, [load]);
  async function generate() { setBusy(true); setError(""); try { const brief = await request<Record<string, unknown>>("/api/sales-intelligence", "POST"); setData((d) => d ? { ...d, brief } : d); } catch (e) { setError(e instanceof Error ? e.message : "Could not generate brief."); } finally { setBusy(false); } }
  async function coach() { setCoachingBusy(true); setError(""); try { setReps(await request("/api/sales-intelligence?section=reps", "POST")); } catch (e) { setError(e instanceof Error ? e.message : "Could not refresh coaching."); } finally { setCoachingBusy(false); } }
  const items = data?.items as Array<{ id: string; type: string; title: string; reason: string; priority: string; dueAt: string | null }> | undefined; const brief = data?.brief as { summary?: string; recommendations?: string[]; generatedAt?: string } | null;
  const repRows = reps?.reps as Array<{ id: string; name: string; metrics: Record<string, number> }> | undefined;
  return <div className="space-y-6">{error && <p role="alert" className="text-sm text-danger">{error}</p>}
    <Card><CardHeader className="flex-col items-start justify-between gap-3 sm:flex-row"><div className="min-w-0"><CardTitle>SHE Software Solutions Daily AI Sales Brief</CardTitle><CardDescription>Generated from today’s authorized CRM data.</CardDescription></div><Button className="shrink-0" onClick={generate} disabled={busy}>{busy ? "Preparing…" : "Generate / refresh brief"}</Button></CardHeader><CardContent>{!data && !error ? <p className="text-sm text-muted-foreground">Loading daily priorities…</p> : brief ? <div className="space-y-2"><p className="break-words text-sm">{brief.summary}</p>{brief.recommendations?.map((x) => <p key={x} className="break-words text-sm text-muted-foreground">• {x}</p>)}{brief.generatedAt && <p className="text-xs text-muted-foreground">Generated {new Date(brief.generatedAt).toLocaleString()}</p>}{Boolean(data?.briefStale) && <p className="text-xs text-warning">CRM activity changed since this brief was generated.</p>}{Boolean(data?.aiUnavailable) && <p className="text-xs text-muted-foreground">AI is unavailable; showing a deterministic CRM summary.</p>}</div> : <p className="text-sm text-muted-foreground">{Boolean(data?.noData) ? "Insufficient CRM data for a brief. Add meetings, tasks, follow-ups, or sales activity." : "No brief generated yet."}</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Today’s sales calendar & priorities</CardTitle><CardDescription>Priorities include a reason and do not change calendar records.</CardDescription></CardHeader><CardContent className="space-y-3">{items?.length ? items.map((x) => <div key={x.type + x.id} className="border-b border-border pb-2"><p className="text-sm font-medium">{x.title} <span className="text-xs uppercase text-muted-foreground">{x.priority} · {x.type}</span></p><p className="text-sm text-muted-foreground">{x.reason}{x.dueAt ? " · " + new Date(x.dueAt).toLocaleTimeString() : ""}</p></div>) : data && <p className="text-sm text-muted-foreground">No meetings, due tasks, or assigned follow-ups today.</p>}</CardContent></Card>
    {canViewReps && <Card><CardHeader className="flex-col items-start justify-between gap-3 sm:flex-row"><div><CardTitle>Sales rep activity · last 30 days</CardTitle><CardDescription>CRM counts and pipeline values, without rankings.</CardDescription></div><Button size="sm" variant="outline" className="shrink-0" onClick={coach} disabled={coachingBusy}>{coachingBusy ? "Reviewing…" : "Generate coaching observations"}</Button></CardHeader><CardContent className="space-y-3">{Boolean(reps?.insufficientData) && <p className="text-sm text-muted-foreground">Insufficient activity for responsible coaching observations.</p>}{Boolean(reps?.aiUnavailable) && <p className="text-sm text-muted-foreground">AI coaching is unavailable; CRM metrics remain available.</p>}{Boolean(reps?.coachingStale) && <p className="text-xs text-warning">CRM metrics changed since coaching was generated.</p>}{repRows?.length ? repRows.map((r) => { const coaching = reps?.coaching as Array<{ userId: string; insight: string }> | null; return <div key={r.id} className="border-b border-border pb-2"><p className="font-medium">{r.name}</p><p className="break-words text-sm text-muted-foreground">{r.metrics.leadsHandled} leads updated · {r.metrics.opportunitiesHandled} open opportunities updated · {r.metrics.activitiesCompleted} activities · {r.metrics.followupsCompleted} completed follow-ups · {r.metrics.meetings} meetings · {r.metrics.opportunityMovements} deal movements · open pipeline {r.metrics.pipelineAmount}</p>{coaching?.find((x) => x.userId === r.id) && <p className="mt-1 text-sm">{coaching.find((x) => x.userId === r.id)?.insight}</p>}</div>; }) : <p className="text-sm text-muted-foreground">No reps are available for this period.</p>}</CardContent></Card>}
  </div>;
}

